using System;
using System.Collections.Generic;
using Verse;
using RimWorld;

namespace RimMind;

public class WeeklyChronicle
{
    // Week identity
    public int dayOfYear;
    public int year;
    public int weekNumber;
    public string season;

    // Colony stats
    public string colonyName;
    public int colonistCountStart;
    public int colonistCountEnd;

    // Events
    public List<ColonyEvent> events = new List<ColonyEvent>();
    public List<ColonyEvent> battles = new List<ColonyEvent>();
    public List<ColonyEvent> raids = new List<ColonyEvent>();

    // Deaths & obituaries
    public List<ColonistDeath> deaths = new List<ColonistDeath>();
    public bool deathlessWeek;
    public bool firstDeath;

    // Milestones
    public List<string> milestones = new List<string>();
    public bool raidMarathon;
    public bool firstRaidSurvived;

    // Mood
    public float averageMood;
    public string moodiestColonist;
    public string happiestColonist;

    // Resources
    public ResourceSnapshot resources;

    // Weather
    public string weatherSummary;
    public string weatherPoem;

    // Content sections (generated by LLM)
    public string headline;
    public string leadParagraph;
    public string obituarySection;
    public string battleReport;
    public string milestoneSection;
    public string weatherSection;
    public string lookingAhead;
    public string editorialOpinion;

    // Colonist voices
    public List<ColonistQuote> quotes = new List<ColonistQuote>();

    // Predictions
    public List<Prediction> predictions = new List<Prediction>();

    // Running joke system
    public List<string> runningJokes = new List<string>();
    public string ongoingJoke; // "continuing our ongoing [joke] coverage"

    // Year-ago memory
    public string yearAgoRecap;

    // Meta
    public int ticksWhenGenerated;
    public bool wasFallback; // true if LLM generation failed
}

public class ChronicleSection
{
    public string title;
    public string emoji;      // "⚔️", "😢", etc.
    public string content;
}

public class ColonyEvent
{
    public string type;      // "death", "raid", "battle", "mental_break", "trade", "milestone", "other"
    public string headline;
    public string description;
    public string colonistInvolved;
    public int day;
}

public class ColonistDeath
{
    public string name;
    public string cause;
    public string killer;     // "raider", "wild animal", "infection", "the cold", etc.
    public int day;
    public string lastWords;
}

public class ColonistQuote
{
    public string colonist;
    public string question;
    public string answer;
    public string mood; // "cheerful", "weary", "defiant", etc.
}

public class Prediction
{
    public string event_;
    public int confidencePct; // 10-95
    public string basis;      // "historical data", "current mood", "raid frequency"
}

public class ResourceSnapshot
{
    public int food;
    public int medicine;
    public int wood;
    public int steel;
    public int colonists;
    public int power;
    public string weather;
}

// Tracks running jokes across weeks
public class RunningJokeTracker : IExposable
{
    public Dictionary<string, int> jokeCount = new Dictionary<string, int>();

    public string GetOngoingJoke()
    {
        if (jokeCount.Count == 0) return null;
        // Return the most frequent joke as the "ongoing" one
        string best = null;
        int bestCount = 0;
        foreach (var kvp in jokeCount)
        {
            if (kvp.Value > bestCount)
            {
                bestCount = kvp.Value;
                best = kvp.Key;
            }
        }
        return best;
    }

    public void AddJoke(string joke)
    {
        if (jokeCount.ContainsKey(joke))
            jokeCount[joke]++;
        else
            jokeCount[joke] = 1;
    }

    public void ExposeData()
    {
        Scribe_Collections.Look(ref jokeCount, "jokeCount");
    }
}
